### ISSUE TITLE
Update the way we handle severity filtering

### ISSUE THREAD

**Issue by jhujasonw** [jhu-library-operations/grype_scan_repo#47]
Grype has a commandline option to set the maximial severity level.  We should use that and use a grep filter for filtering out packages that are "acceptable risks" or "known risks" (Seperate ticket for that coming.)

```json
{
  "use": "issues2jira",
  "data": {
    "url": "https://jhulibraries.atlassian.net/browse/OPS-1621",
    "key": "OPS-1621"
  }
}
```

**Comment by jhujasonw** [comment]
Grype's commandline option only modifies the exit code.  It doesn't filter out packages that are lower than the specified level.  Perhaps this is better behavior?  I suppose one could take the report and filter out themselves, but they would be aware of ALL of the vulnerabilities and can choose to ignore the ones they want.  If they really wanted to, they could use the -f option being created for filtering out packages in the same manner if they want.

**Comment by jhujasonw** [comment]
On second thought, we don't check the exit code of grype and probably won't, so perhaps severity filtering should remain the way it is, listing only the ones you want to see, and the exclusion filter to filter out things that are acceptable security risks.  I could use some second opinion on this...

**Comment by derekbelrose** [comment]
Unless we want a second process to analyze the output, the only viable option we have is to use this '-f' to filter out what we consider acceptable. Maybe use the IT@JH metric for medium and higher?

**Comment by jhujasonw** [comment]
Right now there is:

```
        -s <severity>   The severities to filter for, an egrep pattern.
                        (default: '(Unknown|Negligible|Low|Medium|High|Critical)')
        -f <pkg-filter> Package names to filter out, this is an egrep pattern to EXCLUDE pattern.
```
`-s` is an INCLUSIVE pattern for severities you want to see.  `-f` is an EXCLUSIVE pattern that will filter out packages or security advisory tags you are deeming as acceptable.  I was considering changing `-s` to function like grype's built in "fail-on" function, but it only changes the exit code, which the scanner ignores and only counts the output from grype.  I guess the question is, is the function of these two options to the scanner enough?  Is it ok that we could potentially be filtering out things? I guess the answer is yes, because the user is specifying those filters.  Does that sound reasonable?

**Comment by jhujasonw** [comment]
Looks like @derekbelrose agrees, so I will close this and keep the current behavior for now.
